### ISSUE TITLE
AttributeError: module 'louis' has no attribute 'translateString'

### ISSUE THREAD

**Issue by MinHieu2006** [n-y-kim/louis-python#1]
Hi , nice for your help.
I install this project , and extract them.
Then i run pip setup.py install.
I make new python file.
And use this follow code:
import louis

print(louis.translateString(["braille-patterns.cti", "en-us-g2.ctb"], "Hello, World!"))
and got this error : AttributeError: module 'louis' has no attribute 'translateString'
How to fix it? Thanks!

**Comment by n-y-kim** [comment]
Hi. Can you tell me more specific about your environment & procedure?

And please show me your whole code & error messages

**Comment by MinHieu2006** [comment]
Hi , I don't know which steps i am doing wrong.
So i push my video when i install this project , and working on it.
Sorry for my bad English, and you have a good day!
https://drive.google.com/file/d/1MCsyXoAZduP77YMzziR9Dlwyo4c0Niz5/view?usp=share_link

**Comment by n-y-kim** [comment]
First of all, did you install **'this' project** and installed it? I just looked through your video and the contents inside the liblouis python folder made me assume that...
You should download the zip file from the [original liblouis repo](https://github.com/liblouis/liblouis).
I will keep this issue opened until you resolve this issue.

(And your English is very fine. No need to worry)

**Comment by MinHieu2006** [comment]
I have done it with from [original liblouis repo](https://github.com/liblouis/liblouis)
And I do like in my video. Still got this error
May be this cause problem?
Thank you!
![image](https://user-images.githubusercontent.com/50196971/204080347-8cfbcd4c-5a8d-4329-a42b-adf54bd00817.png)

**Comment by MinHieu2006** [comment]
I have done it with from [original liblouis repo](https://github.com/liblouis/liblouis)
And I do like in my video. Still got this error
May be this cause problem?
Thank you!
![image](https://user-images.githubusercontent.com/50196971/204080366-4dc10be9-ada9-4d87-ae89-5e4892de2760.png)


UPDATE:
I read this from original 
**These bindings use ctypes to access the liblouis shared library. The liblouis shared library needs to be located in the library search path. In most cases, if liblouis has been installed in a standard location on your system, this is already the case and the bindings will work without any additional steps.**

I think may be I push wrong my liblouis folder. Should I push liblouis in python/Lib or some where?

**Comment by n-y-kim** [comment]
Please check one more time if you have downloaded the correct file from the liblouis repo. If you downloaded correctly, the folder structure would look like this:
<img width="880" alt="Screenshot 2022-11-26 at 6 37 03 PM" src="https://user-images.githubusercontent.com/76769919/204082224-d5346e92-68f1-40b5-9d08-81e35ccd1f0b.png">

And you should download the whole zip file for the specific release

<img width="338" alt="Screenshot 2022-11-26 at 6 55 28 PM" src="https://user-images.githubusercontent.com/76769919/204082913-c68f82a5-044f-4104-b407-bf66dcfc830f.png">
<img width="1214" alt="Screenshot 2022-11-26 at 6 55 42 PM" src="https://user-images.githubusercontent.com/76769919/204082915-77c4f3d1-bdc4-4d30-989d-0ddcc8cc3263.png">

After that, you should do [all the steps I have mentioned,](https://github.com/n-y-kim/liblouis-python/blob/main/README.md) such as `./configure`, `make`.. and so on. I could see that you just changed `setup.py.in` to `setup.py`. This is not the correct step. If you followed configure, make, install `setup.py` file would be installed without personal interference.

**Comment by MinHieu2006** [comment]
After i check all, You are right!
I install wrong repo, and install WSl to run ./configure in win.
But I don't understand this

![image](https://user-images.githubusercontent.com/50196971/204091419-91a4d9f0-5578-4e7f-a207-8666b730538c.png)

I don't know what does "Add function CDLL inside from ctypes import ~" mean.
Here my __init__.py file

![image](https://user-images.githubusercontent.com/50196971/204091465-637b8ee8-9699-4058-92e3-968904ba1e91.png)

Is cdll function? And replace  code in line 61 with 
`import os
path_f = os.path.abspath( os.path.join(os.path.dirname(__file__), "liblouis.so.20"))
liblouis = CDLL(path_f)`

Finally , I'm glad to have your help!

**Comment by n-y-kim** [comment]
Hi, glad that you are making progress.
First thing first. Before you make changes at __init__.py, did you have errors(OSError) like I have linked?
If you did not have error, you do not have do this step. 

If there was an error, it's not `cdll`. It's `CDLL`. `CDLL` is a function imported from package `ctype`. So it should all be in a capital letter. Hopes this fix every problem you are facing.

I think this would clear up all the errors you are facing.

**Comment by n-y-kim** [comment]
And you also have to move the `liblouis.so.20` file to where I had specified.

**Comment by MinHieu2006** [comment]
Hi , i have done your tutorial .
In this step , I add CDLL in here (in picture below)

![image](https://user-images.githubusercontent.com/50196971/204118303-e7c1a081-71e3-4571-829a-6b54bad0b06e.png)

And here is my folder
![image](https://user-images.githubusercontent.com/50196971/204118323-387d7a73-6909-4825-a420-4737ad55193c.png)

In python folder 
![image](https://user-images.githubusercontent.com/50196971/204118331-08602a7f-a972-43e7-b23c-8f2e5fb88358.png)

Finally , I run both in my ubuntu and cmd
![image](https://user-images.githubusercontent.com/50196971/204118488-819237de-699f-4476-a0c9-2b3f7c3f8dad.png)

![image](https://user-images.githubusercontent.com/50196971/204118496-07a708ff-5494-4505-84c8-2f706b9c8527.png)

I found solution this problem on [stackoverflow](https://stackoverflow.com/questions/57180580/pyinstaller-win32ctypes-pywin32-pywintypes-error-1920-loadlibraryexw-syst)

May be am wrong in first step?
Thank you a lot

**Comment by n-y-kim** [comment]
The place you are making the test file, `a.py` is wrong.
You should try making them in other folders that do not contain `louis` folder. Because you are keep doing it in `liblouis-3.23.0/python` folder, python get confused which `louis` is it. It should get louis from installed python package library, but it is instead importing from you local `liblouis-3.23.0/python`  folder. This is not about liblouis. It is common knowledge in Python that you should not make a file with the same name of the package you are importing.

What you are doing now which confuses Python:
```
liblouis-3.23.0/python

louis
Makefile.am
Makefil.in
setup.py
setup.py.in
a.py
```

Try changing the path you are testing.

For windows environment, the last OSError message seems disturbing. Maybe it's because of the permission error? I cannot give a solution for this error... maybe try looking up at the original liblouis repo or google. I'm closing this issue as I think you can resolve the issue by yourself now 😉
